import type { MaintenanceTask, MaintenanceLog } from "./maintenance-types"
import { v4 as uuidv4 } from "uuid"

// Mock maintenance tasks
export const maintenanceTasks: MaintenanceTask[] = [
  {
    id: uuidv4(),
    workspaceId: "ws1",
    workspaceName: "Conference Room A",
    title: "Quarterly HVAC Maintenance",
    description: "Regular maintenance of the HVAC system including filter replacement and system check.",
    type: "hvac",
    priority: "medium",
    status: "scheduled",
    scheduledDate: "2024-05-20T09:00:00Z",
    estimatedDuration: 3,
    assignedTo: "tech1",
    assigneeName: "Alex Johnson",
    createdBy: "owner1",
    createdAt: "2024-05-01T14:30:00Z",
    updatedAt: "2024-05-01T14:30:00Z",
    notes: "Please ensure all vents are accessible before the maintenance team arrives.",
    affectsAvailability: true,
    recurrence: "quarterly",
  },
  {
    id: uuidv4(),
    workspaceId: "ws2",
    workspaceName: "Meeting Room B",
    title: "Projector Repair",
    description: "The projector is showing intermittent connection issues with laptops.",
    type: "technology",
    priority: "high",
    status: "in-progress",
    scheduledDate: "2024-05-15T13:00:00Z",
    estimatedDuration: 2,
    assignedTo: "tech2",
    assigneeName: "Sarah Williams",
    createdBy: "owner1",
    createdAt: "2024-05-10T09:15:00Z",
    updatedAt: "2024-05-15T13:30:00Z",
    notes: "IT team is working on this. May need to replace the HDMI ports.",
    affectsAvailability: false,
  },
  {
    id: uuidv4(),
    workspaceId: "ws3",
    workspaceName: "Quiet Office",
    title: "Deep Cleaning",
    description: "Scheduled deep cleaning including carpet shampooing and sanitization.",
    type: "cleaning",
    priority: "medium",
    status: "scheduled",
    scheduledDate: "2024-05-25T18:00:00Z",
    estimatedDuration: 5,
    assignedTo: "clean1",
    assigneeName: "Cleaning Services Inc.",
    createdBy: "owner1",
    createdAt: "2024-05-05T11:20:00Z",
    updatedAt: "2024-05-05T11:20:00Z",
    notes: "To be done after hours. Please ensure all personal items are secured.",
    affectsAvailability: true,
    recurrence: "monthly",
  },
  {
    id: uuidv4(),
    workspaceId: "ws4",
    workspaceName: "Collaboration Space",
    title: "Furniture Replacement",
    description: "Replace worn out chairs and tables with new ergonomic furniture.",
    type: "furniture",
    priority: "low",
    status: "scheduled",
    scheduledDate: "2024-06-05T10:00:00Z",
    estimatedDuration: 4,
    assignedTo: "furn1",
    assigneeName: "Modern Office Supplies",
    createdBy: "owner1",
    createdAt: "2024-05-02T15:45:00Z",
    updatedAt: "2024-05-02T15:45:00Z",
    notes: "New furniture will be delivered between 10 AM and 2 PM.",
    affectsAvailability: true,
  },
  {
    id: uuidv4(),
    workspaceId: "ws1",
    workspaceName: "Conference Room A",
    title: "Lighting Repair",
    description: "Three overhead lights are flickering and need replacement.",
    type: "electrical",
    priority: "medium",
    status: "completed",
    scheduledDate: "2024-05-12T11:00:00Z",
    estimatedDuration: 1.5,
    assignedTo: "elec1",
    assigneeName: "Electrical Maintenance Team",
    createdBy: "owner1",
    createdAt: "2024-05-08T10:10:00Z",
    updatedAt: "2024-05-12T13:00:00Z",
    completedAt: "2024-05-12T12:45:00Z",
    notes: "All lights replaced with energy-efficient LED bulbs.",
    affectsAvailability: false,
    cost: 250,
  },
  {
    id: uuidv4(),
    workspaceId: "ws5",
    workspaceName: "Open Workspace",
    title: "Network Infrastructure Upgrade",
    description: "Upgrading WiFi access points and network switches for better connectivity.",
    type: "technology",
    priority: "high",
    status: "scheduled",
    scheduledDate: "2024-05-18T09:00:00Z",
    estimatedDuration: 8,
    assignedTo: "tech3",
    assigneeName: "Network Solutions Team",
    createdBy: "owner1",
    createdAt: "2024-04-25T16:30:00Z",
    updatedAt: "2024-04-25T16:30:00Z",
    notes: "Will cause intermittent network outages throughout the day.",
    affectsAvailability: true,
  },
  {
    id: uuidv4(),
    workspaceId: "ws2",
    workspaceName: "Meeting Room B",
    title: "Annual Fire Safety Inspection",
    description: "Mandatory annual inspection of fire alarms, extinguishers, and evacuation routes.",
    type: "inspection",
    priority: "high",
    status: "scheduled",
    scheduledDate: "2024-05-30T14:00:00Z",
    estimatedDuration: 2,
    assignedTo: "safety1",
    assigneeName: "Fire Safety Inspector",
    createdBy: "owner1",
    createdAt: "2024-05-03T09:00:00Z",
    updatedAt: "2024-05-03T09:00:00Z",
    notes: "Required by building code. Must be completed before end of month.",
    affectsAvailability: false,
    recurrence: "yearly",
  },
  {
    id: uuidv4(),
    workspaceId: "ws6",
    workspaceName: "Executive Office",
    title: "Plumbing Repair",
    description: "Fix leaking faucet in attached bathroom.",
    type: "plumbing",
    priority: "medium",
    status: "overdue",
    scheduledDate: "2024-05-10T15:00:00Z",
    estimatedDuration: 1,
    assignedTo: "plumb1",
    assigneeName: "Plumbing Services",
    createdBy: "owner1",
    createdAt: "2024-05-05T11:20:00Z",
    updatedAt: "2024-05-05T11:20:00Z",
    notes: "Plumber had emergency and couldn't make it. Need to reschedule.",
    affectsAvailability: false,
  },
]

// Mock maintenance logs
export const maintenanceLogs: MaintenanceLog[] = [
  {
    id: uuidv4(),
    taskId: maintenanceTasks[1].id,
    timestamp: "2024-05-15T13:30:00Z",
    userId: "tech2",
    userName: "Sarah Williams",
    action: "Status updated",
    notes: "Started diagnosing the projector issue. Found loose connection in HDMI port.",
    statusChange: {
      from: "scheduled",
      to: "in-progress",
    },
  },
  {
    id: uuidv4(),
    taskId: maintenanceTasks[4].id,
    timestamp: "2024-05-12T12:45:00Z",
    userId: "elec1",
    userName: "Electrical Maintenance Team",
    action: "Task completed",
    notes: "Replaced all three flickering lights with new LED fixtures. Tested and working properly.",
    statusChange: {
      from: "in-progress",
      to: "completed",
    },
  },
  {
    id: uuidv4(),
    taskId: maintenanceTasks[4].id,
    timestamp: "2024-05-12T11:15:00Z",
    userId: "elec1",
    userName: "Electrical Maintenance Team",
    action: "Status updated",
    notes: "Started work on replacing the lights.",
    statusChange: {
      from: "scheduled",
      to: "in-progress",
    },
  },
  {
    id: uuidv4(),
    taskId: maintenanceTasks[7].id,
    timestamp: "2024-05-11T09:00:00Z",
    userId: "owner1",
    userName: "Admin User",
    action: "Status updated",
    notes: "Plumber didn't show up. Need to reschedule.",
    statusChange: {
      from: "scheduled",
      to: "overdue",
    },
  },
]

// Function to get maintenance tasks for a specific workspace
export function getWorkspaceMaintenanceTasks(workspaceId: string): MaintenanceTask[] {
  return maintenanceTasks.filter((task) => task.workspaceId === workspaceId)
}

// Function to get maintenance logs for a specific task
export function getMaintenanceTaskLogs(taskId: string): MaintenanceLog[] {
  return maintenanceLogs.filter((log) => log.taskId === taskId)
}
